using UnityEngine;

public class BekvamAnimationHandler : MonoBehaviour
{
    bool isAnimationPlaying;
    Animator anim;
    void Start()
    {
        anim = GetComponent<Animator>();
        //anim.Play($"Bekv채m Step {currentStep}");
    }

    void Update()
    {
        //if(isAnimationPlaying) return;
        //anim.Play($"Bekv채m Step {currentStep}");
        //isAnimationPlaying = true;
        PlayAnimation(StepCounter.CurrentStep);
    }

    void PlayAnimation(int index)
    {
        if (index < StepCounter.MaxSteps)
            anim.Play($"Bekv채m Step {index}");
        if (index == StepCounter.MaxSteps)
            anim.Play("Bekv채m Completed");
    }
}
